### ISSUE TITLE
Route.get() requires callback functions but got a [object Undefined]

### ISSUE THREAD

**Issue by ColeWill** [CoolCode2/project-2#2]
trying to move my controllers out of my routes and get this error, but i think i set it up right,
also cannot move the router/controller that serves my homepage, and it only works when its spelled wrong.

http://stackoverflow.com/questions/38237886/node-error-route-get-requires-callback-functions-but-got-a-object-undefined

http://stackoverflow.com/questions/42216932/error-route-get-requires-callback-functions-but-got-a-object-undefined

sendfile vs sendFile
http://stackoverflow.com/questions/26202150/express-js-error-express-deprecated-res-sendfile-use-res-sendfile-instead

**Comment by ZebGirouard** [comment]
Looks like you're off to a good start on this.  Great work, Cole!

**Comment by ColeWill** [comment]
Thanks zeb!
forgot "require" with request,
and added res.sendfile(process.cwd() +'/views/index.html'),

beacuse ('__dirname '+) wouldn't get me to the root directory
