### ISSUE TITLE
Moving post route to controller

### ISSUE THREAD

**Issue by shockeyt** [CoolCode2/project-2#3]
Try this:
In routes.js
router.route('/api/quotes')
  .post(qControllers.postQ)

In qControllers.js
function postQ(req,res){
        res.json("JSON req.body._id:   "+ req.body._id);
  var postQ = new db.Quote
    ({
    
    quote: req.body.quote,
    author: req.body.author
      });
      
    postQ.save(function(err, q){
          res.json(q);
  });
}

Don't forget to module.exports.postQ = postQ;

**Comment by ColeWill** [comment]
can't take controller out of route still

http://stackoverflow.com/questions/34560195/how-to-move-my-controllers-into-a-separate-package-folder-in-laravel-5-2

https://laracasts.com/discuss/channels/general-discussion/how-to-move-my-controllers-into-a-seperate-package-folder

**Comment by ColeWill** [comment]
done
